openapi: 3.0.3
info:
  title: Open Traffic Generator Testbed Model API
  description: |-
    OTG Testbed Model
  version: 0.0.5
  contact:
    url: https://github.com/open-traffic-generator/testbed
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: /
paths: {}
